import { AUTHORED_QUEUE, AUTHORED_SEED, PIECES, SPAWN } from './content';
import { landingTransform, placementValidity } from './geometry';
import { buildDirectedEdges, resolveIntelliRag } from './graph';
import { RULES_VERSION, SCHEMA_VERSION } from './types';
import type { ActivePiece, GameEvent, GameIntent, GameState, PlacedPiece, ReduceResult, Rotation, UndoFrame } from './types';
const spawnAt = (queue: readonly GameState['queue'][number][], index: number): ActivePiece | null => { const pieceId = queue[index]; return pieceId ? { instanceId: `${pieceId}-${index + 1}`, pieceId, transform: SPAWN } : null; };
export const createInitialState = (seed = AUTHORED_SEED): GameState => ({ schemaVersion: SCHEMA_VERSION, rulesVersion: RULES_VERSION, seed, tick: 0, started: false, phase: 'playing', resumePhase: null, queue: AUTHORED_QUEUE, queueIndex: 0, active: spawnAt(AUTHORED_QUEUE, 0), placements: [], undo: [], discoveries: [], removedProvenance: null });
const rejected = (state: GameState, intent: GameIntent['type'], reason: string): ReduceResult => ({ state, events: [{ type: 'intent-rejected', intent, reason }] });
const frame = (s: GameState): UndoFrame => ({ placements: s.placements, active: s.active, queueIndex: s.queueIndex, phase: s.phase, discoveries: s.discoveries, removedProvenance: s.removedProvenance });
const move = (state: GameState, intent: GameIntent, dx: number, dy: number, rotation: Rotation, type: 'piece-moved' | 'piece-rotated'): ReduceResult => { if (!state.active) return rejected(state, intent.type, 'No active piece.'); const transform = { x: state.active.transform.x + dx, y: state.active.transform.y + dy, rotation }; if (placementValidity(PIECES[state.active.pieceId], transform, state.placements) !== 'valid') return rejected(state, intent.type, 'The last legal transform was preserved.'); const active = { ...state.active, transform }; return { state: { ...state, started: true, active }, events: [{ type, instanceId: active.instanceId, transform }] }; };
const place = (state: GameState, intent: 'place' | 'hard-drop'): ReduceResult => { if (!state.active) return rejected(state, intent, 'No active piece.'); const transform = landingTransform(PIECES[state.active.pieceId], state.active.transform, state.placements); const placement: PlacedPiece = { ...state.active, transform }; const placements = [...state.placements, placement]; const before = buildDirectedEdges(state.placements); const edges = buildDirectedEdges(placements); const newEdges = edges.filter((e) => !before.some((p) => p.fromInstanceId === e.fromInstanceId && p.toInstanceId === e.toInstanceId)); const resolution = resolveIntelliRag(placements); const nextIndex = state.queueIndex + 1; const active = resolution ? null : spawnAt(state.queue, nextIndex); const events: GameEvent[] = []; if (intent === 'hard-drop') events.push({ type: 'piece-dropped', instanceId: placement.instanceId, distance: transform.y - state.active.transform.y }); events.push({ type: 'piece-placed', placement }, ...newEdges.map((edge): GameEvent => ({ type: 'connection-created', edge }))); if (resolution) events.push({ type: 'system-resolved', resolution }); else if (active) events.push({ type: 'piece-spawned', piece: active }); return { state: { ...state, started: true, placements, active, queueIndex: nextIndex, undo: [...state.undo, frame(state)], phase: resolution ? 'resolved' : state.phase, discoveries: resolution ? [...new Set([...state.discoveries, 'intellirag'])] : state.discoveries }, events }; };
export const reduceGame = (state: GameState, intent: GameIntent): ReduceResult => {
  if (intent.type === 'resume') return state.phase === 'paused' && state.resumePhase ? { state: { ...state, phase: state.resumePhase, resumePhase: null }, events: [{ type: 'resumed' }] } : rejected(state, intent.type, 'Game is not paused.');
  if (state.phase === 'paused') return rejected(state, intent.type, 'Game is paused.');
  switch (intent.type) {
    case 'move': return move(state, intent, intent.dx, 0, state.active?.transform.rotation ?? 0, 'piece-moved');
    case 'rotate': return move(state, intent, 0, 0, (((state.active?.transform.rotation ?? 0) + intent.direction + 4) % 4) as Rotation, 'piece-rotated');
    case 'soft-drop': return move(state, intent, 0, 1, state.active?.transform.rotation ?? 0, 'piece-moved');
    case 'hard-drop': case 'place': return place(state, intent.type);
    case 'undo': { if (state.phase !== 'playing') return rejected(state, intent.type, 'Only unresolved placements can be undone.'); const previous = state.undo.at(-1); return previous ? { state: { ...state, ...previous, undo: state.undo.slice(0, -1) }, events: [{ type: 'undone' }] } : rejected(state, intent.type, 'Nothing to undo.'); }
    case 'pause': return { state: { ...state, phase: 'paused', resumePhase: state.phase }, events: [{ type: 'paused' }] };
    case 'tick': { if (!state.started || state.phase !== 'playing') return { state, events: [] }; const result = move(state, intent, 0, 1, state.active?.transform.rotation ?? 0, 'piece-moved'); return result.events[0]?.type === 'intent-rejected' ? place({ ...state, tick: state.tick + 1 }, 'place') : { ...result, state: { ...result.state, tick: state.tick + 1 } }; }
    case 'remove-provenance': { if (state.phase !== 'resolved') return rejected(state, intent.type, 'Resolve IntelliRAG first.'); const removed = state.placements.find((p) => p.pieceId === 'provenance'); return removed ? { state: { ...state, phase: 'counterfactual', placements: state.placements.filter((p) => p !== removed), removedProvenance: removed }, events: [{ type: 'counterfactual-started', removed }, { type: 'insight', insightId: 'citation-path-broken' }, { type: 'insight', insightId: 'evaluation-degraded' }] } : rejected(state, intent.type, 'Provenance is not present.'); }
    case 'restore-provenance': { const restored = state.removedProvenance; return state.phase === 'counterfactual' && restored ? { state: { ...state, phase: 'insight-resolved', placements: [...state.placements, restored], removedProvenance: null, discoveries: [...new Set([...state.discoveries, 'provenance-load-bearing', 'document-source'])] }, events: [{ type: 'counterfactual-restored', restored }, { type: 'insight', insightId: 'provenance-load-bearing' }, { type: 'continuation-revealed', conceptId: 'document-source' }] } : rejected(state, intent.type, 'No withheld Provenance piece.'); }
  }
};
