import { describe, expect, it } from 'vitest';
import { BOARD_HEIGHT, BOARD_WIDTH, INTELLIRAG_RECIPE, PIECES, buildDirectedEdges, classifyGhost, createInitialState, reduceGame, replay, resolveIntelliRag, stableStateHash } from '../src/game';
import type { GameIntent, GameState, PieceId, PlacedPiece } from '../src/game';
import { CANONICAL_REPLAY_COMMANDS, CANONICAL_REPLAY_HASH, CANONICAL_REPLAY_SEED } from './fixtures/canonical-replay';
const line = (ids: readonly PieceId[]): readonly PlacedPiece[] => ids.map((pieceId, x) => ({ instanceId: `${pieceId}-${x}`, pieceId, transform: { x: x + 2, y: 15, rotation: 0 } }));
describe('typed content and graph', () => {
  it('defines a 10x16 board and the canonical recipe', () => { expect([BOARD_WIDTH, BOARD_HEIGHT]).toEqual([10, 16]); expect(Object.keys(PIECES)).toEqual(INTELLIRAG_RECIPE.requiredPath); });
  it('builds facing typed directed edges and resolves only the complete path', () => { const placements = line(INTELLIRAG_RECIPE.requiredPath); expect(buildDirectedEdges(placements)).toHaveLength(4); expect(resolveIntelliRag(placements)?.componentInstanceIds).toHaveLength(5); expect(resolveIntelliRag(placements.slice(0, 4))).toBeNull(); });
});
describe('reducer', () => {
  it('preserves immutable snapshots and supports movement, rotation, placement and undo', () => { const initial = createInitialState(); const moved = reduceGame(initial, { type: 'move', dx: -1 }).state; const rotated = reduceGame(moved, { type: 'rotate', direction: 1 }).state; const placed = reduceGame(rotated, { type: 'hard-drop' }).state; expect(initial.active?.transform.x).toBe(4); expect(moved.active?.transform.x).toBe(3); expect(rotated.active?.transform.rotation).toBe(1); expect(placed.placements).toHaveLength(1); expect(reduceGame(placed, { type: 'undo' }).state).toEqual(rotated); });
  it('pauses without hidden ticks', () => { const started = reduceGame(createInitialState(), { type: 'move', dx: 1 }).state; const paused = reduceGame(started, { type: 'pause' }).state; expect(reduceGame(paused, { type: 'tick' }).state).toBe(paused); expect(reduceGame(paused, { type: 'resume' }).state.tick).toBe(started.tick); });
  it('starts gravity on an explicit start intent without altering the board', () => { const initial = createInitialState(); expect(initial.started).toBe(false); const started = reduceGame(initial, { type: 'start' }); expect(started.state.started).toBe(true); expect(started.state.active?.transform).toEqual({ x: 4, y: 0, rotation: 0 }); expect(started.events).toHaveLength(0); expect(reduceGame(started.state, { type: 'start' }).state).toEqual(started.state); });
  it('classifies invalid, incomplete and compatible ghosts', () => { const initial = createInitialState(); expect(classifyGhost(initial, { x: -1, y: 0, rotation: 0 })?.kind).toBe('invalid'); expect(classifyGhost(initial)?.kind).toBe('incomplete'); const state: GameState = { ...initial, active: { instanceId: 'chunking-2', pieceId: 'chunking', transform: { x: 3, y: 0, rotation: 0 } }, placements: line(['ingestion']) }; expect(classifyGhost(state)?.kind).toBe('compatible'); });
  it('resolves then emits causal remove/restore insights', () => { let state = replay(CANONICAL_REPLAY_SEED, CANONICAL_REPLAY_COMMANDS); expect(state.phase).toBe('resolved'); const removed = reduceGame(state, { type: 'remove-provenance' }); expect(removed.events.map((event) => event.type)).toEqual(['counterfactual-started', 'insight', 'insight']); expect(buildDirectedEdges(removed.state.placements)).toHaveLength(2); const restored = reduceGame(removed.state, { type: 'restore-provenance' }); expect(restored.state.phase).toBe('insight-resolved'); expect(restored.state.discoveries).toContain('document-source'); expect(resolveIntelliRag(restored.state.placements)).not.toBeNull(); });
});
describe('property-style invariants and replay', () => {
  it('keeps legal transforms in bounds for generated command sequences', () => { const intents: readonly GameIntent[] = [{ type: 'move', dx: -1 }, { type: 'move', dx: 1 }, { type: 'rotate', direction: 1 }, { type: 'rotate', direction: -1 }, { type: 'soft-drop' }]; for (let mask = 0; mask < 128; mask += 1) { let state = createInitialState(); for (let step = 0; step < 20; step += 1) state = reduceGame(state, intents[(mask * 17 + step * 11) % intents.length]!).state; if (state.active) { expect(state.active.transform.x).toBeGreaterThanOrEqual(0); expect(state.active.transform.x).toBeLessThan(BOARD_WIDTH); expect(state.active.transform.y).toBeGreaterThanOrEqual(0); expect(state.active.transform.y).toBeLessThan(BOARD_HEIGHT); } } });
  it('replays identically and has a stable canonical hash', () => { const first = replay(CANONICAL_REPLAY_SEED, CANONICAL_REPLAY_COMMANDS); const second = replay(CANONICAL_REPLAY_SEED, CANONICAL_REPLAY_COMMANDS); expect(second).toEqual(first); expect(stableStateHash(first)).toBe(CANONICAL_REPLAY_HASH); });
});
